baseURL = "https://smur-photography-gear.netlify.com/"
languageCode = "en-us"
title = "Mon matériel de photographie"
theme =  "book"
disableKinds = ["taxonomy", "taxonomyTerm"]

disablePathToLower = true
enableGitInfo = true

[params]
    # show or hide table of contents for page
    BookShowToC = true
    
    # Set bundle to render side menu
    # if not specified file structure and weights will be used
    BookMenuBundle = "/docs/menu"

    # Set source repository location.
    # Used for 'Last Modified' and 'Edit this page' links.
    BookRepo = "https://github.com/deild/photography-gear"

