baseURL = "https://smur-photography-gear.netlify.com/"
locale = "fr_FR"
title = "Mon matériel de photographie"
theme =  "hugo-book"
disableKinds = ["taxonomy"]

disablePathToLower = true
enableGitInfo = true

[params]
    # show or hide table of contents for page
    BookShowToC = false

    # Set bundle to render side menu
    # if not specified file structure and weights will be used
    BookMenuBundle = "/docs/menu"

    # Set source repository location.
    # Used for 'Last Modified' and 'Edit this page' links.
    BookRepo = "https://github.com/deild/photography-gear"
