language: minimal
before_install:
  - sudo apt-get install build-essential curl file git
install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
  - echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
  - brew update && brew install hugo
script:
  - hugo --gc --minify
branches:
  only:
  - master
  - /^release.*$/
  - /^feature.*$/
  - /^hotfix.*$/
