language: minimal
stages:
  - test
  - name: 'deploy releases'
    if: tag IS present
install:
  - curl -fLo "$HOME/bin/hugo_extended_Linux-64bit.tar.gz" --create-dirs https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_extended_0.56.3_Linux-64bit.tar.gz
  - tar -xzf $HOME/bin/hugo_extended_Linux-64bit.tar.gz -C $HOME/bin
  - $HOME/bin/hugo version
script:
  - $HOME/bin/hugo --gc --minify
jobs:
  include:
    - stage: 'deploy releases'
      after_success:
        - echo '# Journal des modifications' > BODY.md
        - echo "" >> BODY.md
        - if [[ $(git tag -l '*' | wc -l) == "1" ]]; then
            echo "See [Changelog](https://github.com/deild/photography-gear/commits/$TRAVIS_TAG)" >> BODY.md;
          else
            echo "See [Changelog](https://github.com/deild/photography-gear/compare/$(git tag -l '*' | tail -n2 | head -n1)...$TRAVIS_TAG)" >> BODY.md;
          fi
        - curl -fLo "$HOME/bin/gothub.bz2" --create-dirs https://github.com/deild/gothub/releases/download/v0.8.0/linux-amd64-gothub.bz2
        - bunzip2 $HOME/bin/gothub.bz2
        - chmod +x $HOME/bin/gothub
        - $HOME/bin/gothub --version
        - tar -czf www.tar.xz public/
        - sha256sum www.tar.xz > www.tar.xz.sha256
        - $HOME/bin/gothub release -u deild -r photography-gear -t $TRAVIS_TAG -n $TRAVIS_TAG -d - < BODY.md
        - $HOME/bin/gothub upload -u deild -r photography-gear -t $TRAVIS_TAG -n "www.tar.xz" -f www.tar.xz -R
        - $HOME/bin/gothub upload -u deild -r photography-gear -t $TRAVIS_TAG -n "www.tar.xz.sha256" -f www.tar.xz.sha256 -R
