language: minimal
install:
  - curl -fLo "$HOME/bin/hugo_extended_Linux-64bit.tar.gz" --create-dirs https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_extended_0.56.3_Linux-64bit.tar.gz
  - tar -xvzf $HOME/bin/hugo_extended_Linux-64bit.tar.gz -C $HOME/bin
  - $HOME/bin/hugo version
script:
  - $HOME/bin/hugo --gc --minify
before_deploy:
  - printf 'Journal des modification\n\n' > BODY.md
  - if [[ $(git tag -l '*' | wc -l) == "1" ]]; then
      echo "[$TRAVIS_TAG](https://github.com/deild/photography-gear/commits/$TRAVIS_TAG)" >> BODY.md;
    else
      echo "[$TRAVIS_TAG](https://github.com/deild/photography-gear/compare/$(git tag -l '*' | tail -n2 | head -n1)...$TRAVIS_TAG)" >> BODY.md;
    fi
  - export BODY=$(<BODY.md)
  - tar -czf www.tar.xz public/
  - sha256sum www.tar.xz > www.tar.xz.sha256
deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "*.tar.xz"
    - "*.sha256"
  skip_cleanup: true
  body: $BODY
  on:
    repo: deild/photography-gear
    tags: true

branches:
  only:
  - master
  - /^release.*$/
  - /^feature.*$/
  - /^hotfix.*$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
