bin: git
style: github
template: CHANGELOG.tpl.md
info:
  title: Journal des modifications
  repository_url: https://github.com/deild/photography-gear
options:
  commits:
    filters:
      Type:
        - feat # A new feature
        - fix # A bug fix
        - perf # A code change that improves performance
        - refactor # A code change that neither fixes a bug nor adds a feature
        - docs # Documentation only changes
          #- style # Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
          #- test # Adding missing tests or correcting existing tests
        - improvement # improve a current implementation without adding a new feature or fixing a bug
          #- build # Changes that affect the build system or external dependencies
          #- ci # Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
  commit_groups:
    title_maps:
      feat: Fonctionnalités
      fix: Corrections de bugs
      perf: Améliorations de performance
      refactor: Refactorisation du code
      docs: Documentations
      improvement: Améliorations
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
  issues:
    prefix:
      - #
  refs:
    actions:
      - Closes
      - Fixes

