on:
  workflow_dispatch:
    inputs:
      levelOrVersion:
        description: 'Possible level value: major, minor, patch, release, rc, beta, alpha or any valid semver version that is greater than current version'
        required: true
        default: 'patch'

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DEILD_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: |
          git config user.name deild
          git config user.email 8457875+deild@users.noreply.github.com
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          pip install --user --upgrade bump2version
          ~/.local/bin/bump2version --verbose --tag-message "Release {new_version}" ${{ github.event.inputs.levelOrVersion }}
          git push 
          git push --tags
