on:
  workflow_dispatch:
    inputs:
      levelOrVersion:
        description: 'Possible level value: major, minor, patch, release, rc, beta, alpha or any valid semver version that is greater than current version'
        required: true
        default: 'patch'

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DEILD_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          pip install --user --upgrade bump2version
          python -m bump2version --tag-message "Release {new_version}" ${{ github.event.inputs.levelOrVersion }}